default: &default
  adapter: postgres
  encoding: unicode
  host: localhost
  pool: 5

development:
  <<: *default
  database: blog_from_scratch_development
staging:
  <<: *default
  database: blog_from_scratch_development
production:
  <<: *default
  database: phindee
  username: namnh
  password: 123123